# nixpacks.toml (Versi Lengkap Final)

[phases.setup]
nixPkgs = [
    "glib",
    "nss",
    "nspr",
    "gdk-pixbuf",
    "cairo",
    "pango",
    "gtk3",
    "cups",
    "libepoxy",
    "libdrm",
    "mesa",
    "alsa-lib",
    "at-spi2-atk",
    "libxkbcommon",
    "libxcomposite",
    "libxdamage",
    "libxfixes",
    "libxrandr",
    "libxcursor",
    "chromium"
]